image:
  debug: True
persistence:
  size: "5Gi"
wordpressUsername : "wordpress"
wordpressPassword: "ChangeME"
mariadb:
  enabled : false
externalDatabase:
  host: "galera-mariadb-galera.default.svc.cluster.local"
  port: 3306
  user: "root"
  password: "ChangeMe"
  database: "wordpress"