run-name: "${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.TERRAFORM_USERNAME }}
      PASSWORD: ${{ secrets.TERRAFORM_PASSWORD }}
      CLIENT_ID: ${{ secrets.TERRAFORM_CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.TERRAFORM_CLIENT_SECRET }}
      SUBSCRIPTION_ID: ${{ secrets.TERRAFORM_SUBSCRIPTION_ID }}
      RESOURCE_GROUP_NAME: ${{ secrets.TERRAFORM_RESOURCE_GROUP_NAME }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Terraform
        run: |
          cd terraform
          echo 'client_id       = "$CLIENT_ID"' > terraform.tfvars
          echo 'client_secret   = "$CLIENT_SECRET"' >> terraform.tfvars
          az login -u $USERNAME -p $PASSWORD
          terraform init
          terraform state pull
          terraform apply --auto-approve
      - name: Run ansible
        run: |
          ansible --version
