run-name: "${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.TERRAFORM_USERNAME }}
      PASSWORD: ${{ secrets.TERRAFORM_PASSWORD }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Terraform
        run: |
          cd terraform
          az login -u $USERNAME -p $PASSWORD
          terraform init
          terraform apply --auto-approve
      - name: Run ansible
        run: |
          ansible --version
