run-name: "${{ github.actor }} push '${{ github.event.head_commit.message }}' 🚀"
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Terraform
        run: |
          terraform --version
      - name: Run ansible
        run: |
          ansible --version
